---
development:
  cloud_name: hv7qoothw
  api_key: '282962218576484'
  api_secret: S5DLLPVndtdXLmKwVVSSFS5td-Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hv7qoothw
  api_key: '282962218576484'
  api_secret: S5DLLPVndtdXLmKwVVSSFS5td-Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hv7qoothw
  api_key: '282962218576484'
  api_secret: S5DLLPVndtdXLmKwVVSSFS5td-Y
  enhance_image_tag: true
  static_image_support: false
